Resources:
  Ec2Instance: 
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-west-2a
      ImageId: ami-0d608465670dfa77b
      InstanceType: t2.micro
      KeyName: !Ref SSHKey
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files: 
            /tmp/myfile2.txt: 
              content: "/tmp/myfile1.txt"
              mode: "120644"   
        commands:
          test:
            command: "touch file1"  

Parameters:
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
      