Resources:
  Ec2Instance: 
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-west-2a
      ImageId: ami-0d608465670dfa77b
      InstanceType: t2.micro
      KeyName: !Ref SSHKey
  
Parameters:
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
      