Resources:
  Ec2Instance: 
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-west-2a
      ImageId: ami-0d608465670dfa77b
      InstanceType: t2.micro
    Metadata:
      'AWS::ClouFormation::Init':
        config:
          files:
            /tmp/test.txt:
               content: Hello World!
               mode: '000755'
               owner: root
               group: root