Resources:
  Ec2Instance: 
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-west-2a
      ImageId: ami-0d608465670dfa77b
      InstanceType: t2.micro
      UserData:
        Fn::Base64:
           !Sub |
              #!/bin/bash
              sudo yum install httpd -y
              sudo service httpd start
              chkconfig httpd on
      